import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Loader from "./loader";
import Script from "next/script";
import CookieConsent from "@/components/shared/cookie";
import Providers from "./providers";

const aeonik = localFont({
  src: [
    {
      path: "./fonts/Aeonik-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-aeonik",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Purotaja",
  description: "Generated by create next app",
  icons: {
    icon: "/icon512_rounded.png",
    apple: "/icon512_rounded.png",
  },
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          #content { display: none; }
          #loader { display: flex; }
        `}</style>
      </head>
      <body className={aeonik.variable}>
        <div
          id="loader"
          className="fixed inset-0 z-50 flex items-center justify-center bg-white"
        >
          <Loader />
        </div>
        <div id="content">
          <Providers>{children}</Providers>
          <Toaster />
        </div>
        <Script id="show-page" strategy="afterInteractive">
          {`
            function showContent() {
              document.getElementById('loader').style.display = 'none';
              document.getElementById('content').style.display = 'block';
            }
            setTimeout(showContent, 2000);
          `}
        </Script>
        <CookieConsent/>
      </body>
    </html>
  );
}